/**
 * DON template: VerifyWorldId workflow
 *
 * Trigger:
 * - EVM log: WorldIdVerificationRequested(worldIdRequestId, user, nullifierHash, verificationLevel)
 *
 * Steps inside callback:
 * 1. Parse request payload and target user.
 * 2. Resolve original tx calldata if proof is not fully present in event payload.
 * 3. Call World ID verify endpoint:
 *    POST {worldIdVerifyEndpoint}/{worldIdAppId}
 * 4. On success, read current PassRegistry attestation and OR-in flagWorldId.
 * 5. Write PassRegistry.attest(user, ...)
 *
 * NOTE:
 * This file is intentionally TODO-style. Implement using your current CRE TS scaffold generated by:
 *   cre init workflow typescript
 */

export async function main(): Promise<void> {
  throw new Error(
    "TODO: Implement VerifyWorldId workflow with your CRE runtime SDK scaffold and config bindings."
  );
}
