# DON workflow descriptor (template)

user-workflow:
  path: ./main.ts
  workflows:
    staging-settings:
      workflow-name: passstore-verify-asset-staging
      config-file: ./config.staging.json
    production-settings:
      workflow-name: passstore-verify-asset
      config-file: ./config.production.json
