export const kycBrokerAbi = [
  "event KycRequested(uint256 indexed requestId, address indexed user, string levelName)",
  "event KycSyncRequested(uint256 indexed syncRequestId, address indexed user, uint256 indexed requestId)",
  "event WorldIdVerificationRequested(uint256 indexed worldIdRequestId, address indexed user, string nullifierHash, string verificationLevel)",
  "event KybRequested(uint256 indexed kybRequestId, address indexed user, string companyRef, string jurisdiction)",
  "event AssetVerificationRequested(uint256 indexed assetRequestId, uint256 indexed kybRequestId, address indexed user, uint256 chainId, address tokenAddress, uint256 tokenId, uint8 tokenStandard, string symbolOrName, bytes32 metadataHash, string metadataURI)",
  "function setEncryptionPubKey(bytes pubKey)",
  "function encryptionPubKey(address user) view returns (bytes)",
  "function requestKyc(string levelName) returns (uint256 requestId)",
  "function requestKycSync() returns (uint256 syncRequestId)",
  "function requestWorldIdVerification(string proof, string merkleRoot, string nullifierHash, string verificationLevel) returns (uint256 worldIdRequestId)",
  "function requestKyb(string companyRef, string jurisdiction) returns (uint256 kybRequestId)",
  "function requestAssetVerification(uint256 kybRequestId, uint256 chainId, address tokenAddress, uint256 tokenId, uint8 tokenStandard, string symbolOrName, bytes32 metadataHash, string metadataURI) returns (uint256 assetRequestId)",
  "function latestKycRequestId(address user) view returns (uint256)",
  "function hasKycRequest(address user) view returns (bool)",
  "function latestKybRequestId(address user) view returns (uint256)",
  "function hasKybRequest(address user) view returns (bool)",
  "function getPacket(uint256 requestId) view returns (address user, bytes ciphertext, uint64 expiresAt, bool consumed, bool exists)",
  "function markConsumed(uint256 requestId)",
  "function kybRequestOwner(uint256 kybRequestId) view returns (address)"
] as const;
